// Full customer object returned from the API.
export type Customer = {
  id: string; // UUID from the database
  first_name: string;
  last_name: string;

  // address is optional because sometimes it may be missing/empty
  address?: string;
  ph_number: string;
  email: string;
  driving_licence: string;
};

// Body for POST /customers
// Excludes the id since it's generated by the backend.
export type CustomerCreate = Omit<Customer, "id">;

// Body for PATCH /customers/:id
// All fields are optional since it's a partial update.
export type CustomerUpdate = Partial<CustomerCreate>;