FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libpq-dev \
    libpqxx-dev \
    libasio-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /shareddocker

CMD ["bash"]
